heat_template_version: 2017-02-24
description: Kubernetes node definition
parameters:
    index:
        type: number
        label: Index
        description: Index in floating IP list
    key_name:
        type: string
        label: Key Name
        description: SSH key to be used for all instances
    image:
        type: string
        label: Image
        description: Image to be used
    flavor:
        type: string
        label: Instance Type
        description: Type of instance (flavor) to deploy node
    floating_ips:
        type: comma_delimited_list
        label: Floating IP IDs
        description: Floating IP for node
    name:
        type: string
        label: Instance Name
        description: Name of the node
    internal_net:
        type: string
        label: Internal Network
        description: Network to connect node to
    install_script:
        type: string
        label: Install Script
        description: Script to run after cloud-init finishes
    additional_config:
        type: string
        label: Additional Config
        description: Additional software config
        default: ""
conditions:
    empty_additional_config:
        equals:
            - { get_param: additional_config }
            - ""
resources:
    port:
        type: OS::Neutron::Port
        properties:
            admin_state_up: true
            network_id: { get_param: internal_net }
            allowed_address_pairs:
                - ip_address: 10.0.0.0/8
    floatingip_association:
        type: OS::Neutron::FloatingIPAssociation
        properties:
            floatingip_id: { get_param: [ floating_ips, { get_param: index } ] }
            port_id: { get_resource: port }
    instance:
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor: { get_param: flavor }
            key_name: { get_param: key_name }
            networks:
                - port: { get_resource: port }
            name: { get_param: name }
            user_data_format: SOFTWARE_CONFIG
            user_data: { get_resource: user_data }
    user_data_base:
        type: OS::Heat::CloudConfig
        properties:
            cloud_config:
                #cloud-config
                manage_etc_hosts: localhost
                #package_upgrade: true
                packages:
                - kubeadm=1.8.7-00
                - kubernetes-cni=0.5.1-00
                - kubelet=1.8.7-00
                - kubectl=1.8.7-00
                #- docker-ce=17.03.2~ce-0~ubuntu-xenial
                apt_sources:
                    docker.list:
                        source: "deb https://download.docker.com/linux/ubuntu xenial stable"
                        key: { get_file: docker.pgp }
                    kubernetes.list:
                        source: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
                        key: { get_file: kubernetes.pgp }
                runcmd:
                    - - 'systemd-run'
                      - '--on-boot=0s'
                      - '--unit=kubeadm-install'
                      - 'bash'
                      - '-c'
                      - { get_param: install_script }
    user_data:
        type: OS::Heat::MultipartMime
        properties:
            parts:
                if: 
                    - empty_additional_config
                    - - config: { get_resource: user_data_base }
                    - - config: { get_resource: user_data_base }
                      - config: { get_param: additional_config }
outputs:
    ip_address:
        description: IP address of the node
        value: { get_attr: [instance, first_address] }
