heat_template_version: 2017-02-24
description: Kubernetes slave definition
parameters:
    index:
        type: number
        label: Index
        description: Slave index
    key_name:
        type: string
        label: Key Name
        description: SSH key to be used for all instances
    image:
        type: string
        label: Image
        description: Image to be used
    slave_flavor:
        type: string
        label: Slave Instance Type
        description: Type of instance (flavor) to deploy slave nodes
    slave_floating_ips:
        type: comma_delimited_list
        label: Slave Floating IP IDs
        description: Floating IP for slave nodes
    slave_name:
        type: string
        label: Slave Instance Name
        description: Name of slave instance
    internal_net:
        type: string
        label: Internal Network
        description: Network to connect slave to
    master_ip:
        type: string
        label: Master IP
        description: Master node IP address
    token:
        type: string
        label: Token
        description: kubeadm token
resources:
    slave_port:
        type: OS::Neutron::Port
        properties:
            admin_state_up: true
            network_id: { get_param: internal_net }
            allowed_address_pairs:
                - ip_address: 10.0.0.0/8
    slave_floatingip_association:
        type: OS::Neutron::FloatingIPAssociation
        properties:
            floatingip_id: { get_param: [ slave_floating_ips, { get_param: index } ] }
            port_id: { get_resource: slave_port }
    slave_instances:
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor: { get_param: slave_flavor }
            key_name: { get_param: key_name }
            networks:
                - port: { get_resource: slave_port }
            name: { get_param: slave_name }
            user_data_format: SOFTWARE_CONFIG
            user_data: { get_resource: slave_user_data }
    slave_user_data:
        type: OS::Heat::CloudConfig
        properties:
            cloud_config:
                #cloud-config
                manage_etc_hosts: localhost
                #package_upgrade: true
                packages:
                - kubeadm=1.8.7-00
                - kubernetes-cni=0.5.1-00
                - kubelet=1.8.7-00
                - kubectl=1.8.7-00
                #- docker-ce=17.03.2~ce-0~ubuntu-xenial
                apt_sources:
                    docker.list:
                        source: "deb https://download.docker.com/linux/ubuntu xenial stable"
                        key: { get_file: docker.pgp }
                    kubernetes.list:
                        source: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
                        key: { get_file: kubernetes.pgp }
                runcmd:
                    - - 'systemd-run'
                      - '--on-boot=0s'
                      - '--unit=kubeadm-install'
                      - 'bash'
                      - '-c'
                      - str_replace:
                            params:
                                $token: { get_param: token }
                                $master_ip: { get_param: master_ip }
                            template: { get_file: slave.sh }
